### ISSUE TITLE
ДЗ -6  Правки

### ISSUE THREAD

**Issue by Dexter19** [YoliLancaster/Future-in-IT#3]
В файлі стилів (пункт 12 ) має бути 
	:root {
      --main-color: #009;
      --anchor-color: #333;
      --anchor-active-color: salmon;
		--primary-text-color: #000;
		--primary-bg-color: #fff;
		--primary-font-family: 'Roboto', sans-serif; 
		--primary-font-size: 0.875rem / 1.4;
	}

замість 

:root {
  --primary-text-color: #000;
  --primary-bg-color: #fff;
  --primary-font-family: "Roboto", sans-serif;
  --primary-font-size: 0.875rem;
}

**Comment by YoliLancaster** [comment]
Done
